module.exports=[
	{money:0.01,title:'一分钱也是爱'},
	{money:0.66,title:'恭喜恭喜'},
	{money:1.21,title:'一路大步向前进'},
	{money:1.23,title:'业绩一路攀升'},
	{money:1.68,title:'一直发发发'},
	{money:1.77,title:'向革命战友学习'},
	{money:1.99,title:'和客户长长久久'},
	{money:3.45,title:'一直领先不落后'}
]